// <auto-generated />
namespace IntroductoryProject3._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class M : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M));
        
        string IMigrationMetadata.Id
        {
            get { return "202002281549259_M"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
